### ISSUE TITLE
!whoops command works in reverse

### ISSUE THREAD

**Issue by CasperZBang** [jakobmulvad/foosball-rankings#3]
When using the !whoops command the points are added to the winner again, and subtracted from the loser again, instead of reversing like it should.

**Comment by jakobmulvad** [comment]
Are you sure? there is a test that specifically tests for this: https://github.com/jakobmulvad/elo-rankings/blob/master/test/api.test.js#L190

**Comment by CasperZBang** [comment]
Perhaps it just reported wrong?

First the match was reported:
![image](https://user-images.githubusercontent.com/9316478/29918840-4fd07c22-8e47-11e7-9718-17e94e435d46.png)

Then the rollback
![image](https://user-images.githubusercontent.com/9316478/29918855-5daa8a54-8e47-11e7-90ef-36b8a3bbdaa2.png)

It seems that the new elo for czb is higher than after the match, where it should be the opposite

**Comment by jakobmulvad** [comment]
Thank you for reporting this. Yes the ELO was reported incorrectly (but stored correctly in the database)

Fixed in v3.3.2
